version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ist
    ports:
      - "8080:5432"
    networks:
      - test-networks

  service-authentication:
    image: service-authentication:0.0.1-SNAPSHOT
    container_name: service-authentication
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/ist
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8081:8080"
    networks:
      - test-networks

networks:
  test-networks:
    driver: bridge
